name: (Generic Skip) Test contracts workflow
# Handles skipped but required checks

on:
  pull_request:
    paths-ignore:
      - "packages/contracts/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No tests required" '
