name: Test contracts (Generic Skip)
# Handles skipped but required checks

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize', 'ready_for_review']
    branches: ['main', 'dev', 'KIP-3']
    paths-ignore:
      - "packages/contracts/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No tests required" '
