name: Test contracts (Generic Skip) 
# Handles skipped but required checks

on:
  pull_request:
    paths-ignore:
      # In future file changes, we can uncomment the following line
      - ".github/workflows/generic-skip.yml"
      - ".github/workflows/test-contracts.yml"
      - "packages/contracts/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No tests required" '
